pipeline {
    agent any

    environment {
        IMAGE_NAME = "sadikshaik21/task27-app"
        EC2_IP = "100.53.112.206"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME -f Task27-Jenkins-CICD/Dockerfile Task27-Jenkins-CICD/.'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS')]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "
                    docker pull $IMAGE_NAME &&
                    docker stop task27-app || true &&
                    docker rm task27-app || true &&
                    docker run -d --name task27-app -p 80:80 $IMAGE_NAME
                    "
                    '''
                }
            }
        }
    }
}
