pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sadikshaik21/task30-app:latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Pulling the latest source files...'
            }
        }

        stage('Gitleaks Secret Scan') {
            steps {
                echo 'Running gitleaks to sweep for exposed credentials or API keys...'
                sh 'gitleaks detect --verbose' 
            }
        }

        stage('OWASP Dependency Scan') {
            steps {
                echo 'Invoking owasp dependency check via Maven...'
                // Pointing to your exact nested folder where pom.xml sits
                dir('Task30-Full-Secure-Pipeline/Task30-Full-Secure-Pipeline') {
                    sh 'mvn org.owasp:dependency-check-maven:check -DautoUpdate=false'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Compiling resources and building the Docker container layout...'
                // Pointing to your exact nested folder where the Dockerfile sits
                dir('Task30-Full-Secure-Pipeline/Task30-Full-Secure-Pipeline') {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline execution phase completed.'
        }
    }
}