stage('Gitleaks Secret Scan') {
            steps {
                echo 'Downloading and running Gitleaks...'
                sh '''
                    curl -sSLo gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
                    tar -xzf gitleaks.tar.gz gitleaks
                    chmod +x gitleaks
                    ./gitleaks detect --source . --verbose --exit-code=0
                '''
            }
        }