pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        IMAGE_NAME = "secure-app"
    }

    stages {

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Tool Install') {
            steps {
                sh '''
                    java -version || true
                    mvn -version || true
                    git --version || true
                    curl --version || true
                '''
            }
        }

        stage('Clone Repository') {
            steps {
                sh '''
                    echo "Repository already checked out by Jenkins."
                    pwd
                    ls -la
                '''
            }
        }

        stage('Gitleaks Scan') {
            steps {
                sh '''
                    rm -rf gitleaks
                    git clone https://github.com/gitleaks/gitleaks.git
                    echo "Running Gitleaks..."
                '''
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '--scan .', odcInstallation: 'OWASP-Dependency-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "Simulating Docker Build..."
                    echo "docker build -t ${IMAGE_NAME}:latest ."
                '''
            }
        }

        stage('Trivy Security Scan') {
            steps {
                dir('/tmp') {
                    sh '''
                        echo "Downloading Trivy..."

                        rm -f trivy trivy.tar.gz

                        curl -L -o trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v0.72.0/trivy_0.72.0_Linux-64bit.tar.gz

                        ls -lh trivy.tar.gz

                        tar -xzf trivy.tar.gz

                        chmod +x trivy

                        ./trivy --version

                        echo "Running Trivy Scan..."

                        ./trivy fs --exit-code 0 --severity HIGH,CRITICAL $WORKSPACE
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline Completed.'
        }

        success {
            echo 'Build Successful!'
        }

        failure {
            echo 'Build Failed!'
        }
    }
}